content:
  - name: portfolio
    label: Portfolio
    path: src/content/portfolio
    filename: '{fields.title}.md'
    type: collection
    view:
      fields: []
    fields:
      - name: title
        label: Title
        type: text
      - name: description
        label: Description
        type: rich-text
      - name: publishDate
        label: Publish Date
        type: date
      - name: updatedDate
        label: Updated Date
        type: date
      - name: image
        label: Image
        type: image
      - name: featured
        label: Featured
        type: boolean
        default: true
      - name: technologies
        label: Technologies
        type: select
        options:
          creatable: true
          multiple: true
          values: [React, Vue.js, Angular, Node.js, Python, JavaScript, TypeScript, CSS, HTML]
      - name: github
        label: GitHub URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: liveUrl
        label: Live URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: order
        label: Order
        type: number
        options:
          min: 0

media:
  input: public/media
  output: /media
    