content:
  - name: portfolio
    label: Portfolio
    path: src/content/portfolio
    filename: '{fields.title}.md'
    type: collection
    view:
      fields: [ title, description, startDate, endDate, publishDate ]
    fields:
      - name: title
        label: Title
        type: text
        required: true
        description: "The title of the project, e.g., 'My Awesome Project'"
      - name: description
        label: Description
        type: text
        # required: true
        description: "A brief description of the project, e.g., 'This project is about ...'"
      - name: "startDate"
        label: "Project Start Date"
        type: "date"
        required: true
        description: "When the project was started, always fill day with 1st of the month"
      - name: "endDate"
        label: "Project End Date"
        type: "date"
        required: false
        description: "When the project was completed (leave empty for ongoing projects), always fill day with end of the month"
      - name: publishDate
        label: Publish Date
        type: date
        description: "The date when the project was published, e.g., '2023-10-01'"
      - name: updatedDate
        label: Updated Date
        type: date
        description: "The date when the project was last updated, e.g., '2023-10-15'"
      - name: image
        label: Image
        type: image
        description: "An image representing the project, e.g., a screenshot or logo"
      - name: featured
        label: Featured
        type: boolean
        default: true
        description: "Whether the project is featured on the portfolio page"
      - name: technologies
        label: Technologies
        type: select
        options:
          creatable: true
          multiple: true
          values: [React, Vue.js, Angular, Node.js, Python, JavaScript, TypeScript, CSS, HTML, PHP, Laravel, Codeigniter 3, Codeigniter 4, JQuery]
        description: "Technologies used in the project, e.g., 'React, Node.js, CSS'"
      - name: github
        label: GitHub URL
        type: string
        # pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
        description: "The URL to the project's GitHub repository, e.g., '
      - name: liveUrl
        label: Live URL
        type: string
        # pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
        description: "The live URL of the project, e.g., 'https://my-awesome-project.com'"
      - name: order
        label: Order
        type: number
        options:
          min: 0
      - name: body
        label: Body
        type: rich-text
        description: "The main content of the project, can include images, code snippets, and other rich text elements"

  - name: article
    label: Articles
    path: src/content/article
    filename: '{fields.title}.md'
    type: collection
    view:
      fields: []
    fields:
      - name: title
        label: Title
        type: text
      - name: description
        label: Description
        type: text
      - name: pubDate
        label: Publish Date
        type: date
      - name: updatedDate
        label: Updated Date
        type: date
      - name: author
        label: Author
        type: text
      - name: featuredImage
        label: Image
        type: image
      - name: category
        label: Category
        type: text
      - name: tags
        label: Tags
        type: select
        options:
          creatable: true
          multiple: true
          values: []
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: minutesRead
        label: Minutes Read
        type: number
        options:
          min: 0
      - name: body
        label: Body
        type: rich-text

  - name: blog
    label: Blog
    path: src/content/blog
    filename: '{fields.title}.md'
    type: collection
    view:
      fields: []
    fields:
      - name: title
        label: Title
        type: text
      - name: excerpt
        label: Excerpt
        type: text
      - name: pubDate
        label: Publish Date
        type: date
      - name: createdAt
        label: Created At
        type: date
      - name: updatedAt
        label: Updated At
        type: date
      - name: author
        label: Author
        type: text
      - name: category
        label: Category
        type: text
      - name: categoryColor
        label: Category Color
        type: text
      - name: featuredImg
        label: Featured Image
        type: image
      - name: tags
        label: Tags
        type: select
        options:
          creatable: true
          multiple: true
          values: []
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: minutesRead
        label: Minutes Read
        type: number
        options:
          min: 0
      - name: body
        label: Body
        type: rich-text

media:
  input: public/media
  output: /media
    